### PR TITLE
Fix secure storage when running in browser (issue #76)

### PR DESCRIPTION
**Pull request by rbarriuso**
Fix secure storage when running in browser (issue #76).
Update dependencies.
Use local dependencies rather than global.
Update project info.
Minor refactor.

NOTE: requires running `npm i`

### CODE REVIEW

**Comment by rbarriuso** [comment]
Please @rdemera review and test

**Comment by rbarriuso** [comment]
With this changes `npm start` and `npm run start:browser` work again.

**Comment by rbarriuso** [comment]
This PR was tested with NodeJS 10 (v10.19.0)

**Comment by VictorNS69** [comment]
I think this PR must go to **develop** instead of master.

**Comment by rbarriuso** [comment]
> I think this PR must go to **develop** instead of master.

Changed

**Pull request merged**
